# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myproto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'myproto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\x12\x06\x66\x65\x64\x61vg\"B\n\x0bModelUpdate\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\"/\n\rModelResponse\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\",\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\"\x0e\n\x0c\x45mptyRequest2\x80\x01\n\nAggregator\x12\x33\n\x0fSendModelUpdate\x12\x13.fedavg.ModelUpdate\x1a\x0b.fedavg.Ack\x12=\n\x0eGetGlobalModel\x12\x14.fedavg.EmptyRequest\x1a\x15.fedavg.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELUPDATE']._serialized_start=25
  _globals['_MODELUPDATE']._serialized_end=91
  _globals['_MODELRESPONSE']._serialized_start=93
  _globals['_MODELRESPONSE']._serialized_end=140
  _globals['_ACK']._serialized_start=142
  _globals['_ACK']._serialized_end=186
  _globals['_EMPTYREQUEST']._serialized_start=188
  _globals['_EMPTYREQUEST']._serialized_end=202
  _globals['_AGGREGATOR']._serialized_start=205
  _globals['_AGGREGATOR']._serialized_end=333
# @@protoc_insertion_point(module_scope)
